
###

http://localhost:3031/winereview

###

POST http://localhost:3031/winereview
Content-Type: application/json

{
  "wine": "wine-6", 
  "rating": 5,
  "author": "nikolav"
}

###

DELETE http://localhost:3031/chat/6292c00a271d420da5c26599

###
